# Generated by Django 5.2.3 on 2025-08-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "musicbrainz_recordingid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("artist", models.CharField(max_length=255)),
                ("album", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
                ("duration", models.FloatField()),
                ("country", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=255)),
                ("danceability", models.FloatField()),
                ("aggressiveness", models.FloatField()),
                ("happiness", models.FloatField()),
                ("sadness", models.FloatField()),
                ("relaxedness", models.FloatField()),
                ("partyness", models.FloatField()),
                ("acousticness", models.FloatField()),
                ("electronicness", models.FloatField()),
                ("instrumentalness", models.FloatField()),
                ("tonality", models.FloatField()),
                ("brightness", models.FloatField()),
            ],
        ),
    ]
