# Generated by Django 5.2.1 on 2025-06-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("lyrics", models.TextField()),
                ("tfidf", models.JSONField()),
            ],
        ),
    ]
