# Generated by Django 5.2.1 on 2025-06-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
