# Generated by Django 5.2.3 on 2025-08-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="genre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
