# Generated by Django 5.2.3 on 2025-08-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0002_alter_track_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="genre",
            field=models.CharField(max_length=255),
        ),
    ]
