# Generated by Django 5.2.1 on 2025-06-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0002_alter_song_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="tfidf",
        ),
    ]
