# Generated by Django 5.2.3 on 2025-08-11 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0003_alter_track_country_alter_track_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "musicbrainz_artistid",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="track",
            name="artist",
        ),
        migrations.AlterField(
            model_name="track",
            name="musicbrainz_recordingid",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="TrackArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommend_api.artist",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommend_api.track",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="track",
            name="artists",
            field=models.ManyToManyField(
                through="recommend_api.TrackArtist", to="recommend_api.artist"
            ),
        ),
    ]
