# Generated by Django 5.2.3 on 2025-07-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_api', '0003_remove_song_tfidf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
