# Generated by Django 5.2.3 on 2025-07-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_api', '0004_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='acousticness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='aggressiveness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='brightness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='danceability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='electronicness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='happiness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='instrumentalness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='partyness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='relaxedness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='sadness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='tonality',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
