# Generated by Django 5.2.3 on 2025-08-12 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0004_artist_remove_track_artist_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "musicbrainz_albumid",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="track",
            name="country",
        ),
        migrations.RemoveField(
            model_name="track",
            name="release_date",
        ),
        migrations.AlterUniqueTogether(
            name="trackartist",
            unique_together={("track", "artist")},
        ),
        migrations.AlterField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recommend_api.album",
            ),
        ),
        migrations.CreateModel(
            name="AlbumArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommend_api.album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommend_api.artist",
                    ),
                ),
            ],
            options={
                "unique_together": {("artist", "album")},
            },
        ),
        migrations.AddField(
            model_name="album",
            name="artists",
            field=models.ManyToManyField(
                through="recommend_api.AlbumArtist", to="recommend_api.artist"
            ),
        ),
    ]
