# Generated by Django 5.2.3 on 2025-07-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_api', '0005_track_acousticness_track_aggressiveness_track_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='musicbrainz_recordingid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
