# Generated by Django 5.2.3 on 2025-08-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "recommend_api",
            "0005_album_remove_track_country_remove_track_release_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="acousticness",
        ),
        migrations.RemoveField(
            model_name="track",
            name="aggressiveness",
        ),
        migrations.RemoveField(
            model_name="track",
            name="brightness",
        ),
        migrations.RemoveField(
            model_name="track",
            name="danceability",
        ),
        migrations.RemoveField(
            model_name="track",
            name="electronicness",
        ),
        migrations.RemoveField(
            model_name="track",
            name="happiness",
        ),
        migrations.RemoveField(
            model_name="track",
            name="instrumentalness",
        ),
        migrations.RemoveField(
            model_name="track",
            name="partyness",
        ),
        migrations.RemoveField(
            model_name="track",
            name="relaxedness",
        ),
        migrations.RemoveField(
            model_name="track",
            name="sadness",
        ),
        migrations.RemoveField(
            model_name="track",
            name="tonality",
        ),
    ]
