# Generated by Django 5.2.3 on 2025-08-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0006_remove_track_acousticness_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="musicbrainz_albumid",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="artist",
            name="musicbrainz_artistid",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="track",
            name="musicbrainz_recordingid",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
