# Generated by Django 5.2.3 on 2025-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0007_alter_album_musicbrainz_albumid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="file_path",
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
