# Generated by Django 5.2.3 on 2025-08-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0008_track_file_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="genre",
            new_name="genre_dortmund",
        ),
        migrations.AddField(
            model_name="track",
            name="genre_rosamerica",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
