# Generated by Django 5.2.3 on 2025-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0009_rename_genre_track_genre_dortmund_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="musicbrainz_albumid",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="artist",
            name="musicbrainz_artistid",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="track",
            name="artists",
            field=models.ManyToManyField(
                related_name="artists",
                through="recommend_api.TrackArtist",
                to="recommend_api.artist",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="musicbrainz_recordingid",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
