# Generated by Django 5.2.3 on 2025-09-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0010_alter_album_musicbrainz_albumid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="file_path",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
