# Generated by Django 5.2.3 on 2025-09-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0011_alter_track_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="submissions",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
