# Generated by Django 5.2.3 on 2025-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0012_track_submissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
