# Generated by Django 5.2.3 on 2025-09-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0013_alter_album_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="artists",
            field=models.ManyToManyField(
                related_name="tracks",
                through="recommend_api.TrackArtist",
                to="recommend_api.artist",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="title",
            field=models.TextField(),
        ),
    ]
