# Generated by Django 5.2.3 on 2025-09-10 15:09

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_api", "0015_enable_trigram"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="album",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="album_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="artist_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="track_title_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
