# Generated by Django 5.2.3 on 2025-09-12 15:44

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "recommend_api",
            "0016_album_album_name_trgm_artist_artist_name_trgm_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="album",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["name"],
                name="album_name_trgm_gist",
                opclasses=["gist_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["name"],
                name="artist_name_trgm_gist",
                opclasses=["gist_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["title"],
                name="track_title_trgm_gist",
                opclasses=["gist_trgm_ops"],
            ),
        ),
    ]
