from django.db import models

class Track(models.Model):
    musicbrainz_recordingid = models.CharField(primary_key=True, max_length=255)
    artist = models.CharField(max_length=255)
    album = models.CharField(blank=True, null=True, max_length=255)
    title = models.CharField(max_length=255)
    release_date = models.DateField()
    duration = models.FloatField()
    country = models.CharField(blank=True, null=True, max_length=255)
    genre = models.CharField(max_length=255)
    danceability = models.FloatField()
    aggressiveness = models.FloatField()
    happiness = models.FloatField()
    sadness = models.FloatField()
    relaxedness = models.FloatField()
    partyness = models.FloatField()
    acousticness = models.FloatField()
    electronicness = models.FloatField()
    instrumentalness = models.FloatField()
    tonality = models.FloatField()
    brightness = models.FloatField()